<template>
  <div class="analysis-tab">
    <div v-if="loadingReadme" class="loading-container">
      <el-icon class="loading-icon"><Loading /></el-icon>
      <p>{{ store.t('Analyzing README using AI...') }}</p>
    </div>
    
    <!-- AI README Analysis & Charts Row -->
    <el-row :gutter="24" class="content-row" v-else-if="readmeAnalysis">
      <el-col :span="24">
        <el-card class="list-card ai-dashboard-card glass-panel">
          <template #header>
            <div class="card-header ai-header-row">
              <span class="ai-header-title">{{ store.t('AI Assistant - Project Overview') }}</span>
              <!--<el-tag type="warning" size="small" effect="dark">{{ store.t('Gemini 2.5 Active') }}</el-tag>-->
            </div>
          </template>
          
          <el-row :gutter="24">
            <el-col :xs="24" :md="15">
              <div class="ai-overview">
                <h3 class="ai-title">{{ readmeAnalysis.projectName }}</h3>
                <p class="ai-summary">{{ readmeAnalysis.summary }}</p>
                
                <div class="ai-section">
                  <div class="ai-section-title">{{ store.t('Architecture') }}</div>
                  <p class="ai-architecture">{{ readmeAnalysis.architecture }}</p>
                </div>

                <div class="ai-section">
                  <div class="ai-section-title">{{ store.t('Tech Stack') }}</div>
                  <div class="tech-tags">
                    <el-tag
                      v-for="tech in readmeAnalysis.techStack"
                      :key="tech"
                      size="default"
                      type="success"
                      class="tech-tag"
                      effect="plain"
					  round
                    >
                      {{ tech }}
                    </el-tag>
                  </div>
                </div>

                <div class="ai-section">
                  <div class="ai-section-title">{{ store.t('Key Features') }}</div>
                  <ul class="features-list">
                    <li v-for="feat in readmeAnalysis.features" :key="feat" class="feat-item">{{ feat }}</li>
                  </ul>
                </div>
              </div>
            </el-col>
            
            <el-col :xs="24" :md="9">
              <div class="ai-charts-container">
                <div class="ai-section-title">{{ store.t('Score & Structural Breakdown') }}</div>
                
                <!-- Complexity score dial -->
                <div class="complexity-score-box">
                  <div class="complexity-lbl">{{ store.t('Complexity Score') }}</div>
                  <el-progress 
                    type="dashboard" 
                    :percentage="readmeAnalysis.complexityScore" 
                    :color="progressColors"
                    :stroke-width="12"
                  />
                </div>

                <!-- Custom charts generated by Gemini -->
                <div class="custom-bar-charts">
                  <div class="complexity-lbl" style="margin-bottom: 12px;">{{ store.t('Module Distribution') }}</div>
                  <div v-for="chart in readmeAnalysis.charts" :key="chart.name" class="custom-chart-row">
                    <div class="chart-label-row">
                      <span class="chart-name">{{ chart.name }}</span>
                      <span class="chart-value">{{ chart.value }}%</span>
                    </div>
                    <el-progress :percentage="chart.value" :show-text="false" :stroke-width="8" status="warning" />
                  </div>
                </div>
              </div>
            </el-col>
          </el-row>
        </el-card>
      </el-col>
    </el-row>
    
    <div v-else class="loading-container">
      <p>{{ store.t('No README analysis data available from AI.') }}</p>
    </div>
  </div>
</template>

<script setup lang="ts">
import { store } from '../../stores';
import { Loading } from '@element-plus/icons-vue';

defineProps<{
  readmeAnalysis: any;
  loadingReadme: boolean;
}>();

const progressColors = [
  { color: '#f56c6c', percentage: 20 },
  { color: '#e6a23c', percentage: 40 },
  { color: '#5cb87a', percentage: 60 },
  { color: '#1989fa', percentage: 80 },
  { color: '#6f7ad3', percentage: 100 },
];
</script>

<style scoped>
.loading-container {
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
  padding: 4rem 0;
  color: var(--text-muted);
}

.loading-icon {
  font-size: 2rem;
  margin-bottom: 0.5rem;
  animation: rotating 2s linear infinite;
}

.ai-dashboard-card {
  margin-top: 1.5rem;
}

.ai-header-row {
  display: flex;
  justify-content: space-between;
  align-items: center;
}

.ai-header-title {
  font-weight: 600;
  color: var(--text-primary);
}

.ai-overview {
  display: flex;
  flex-direction: column;
  gap: 1.5rem;
}

.ai-title {
  margin: 0;
  font-size: 1.5rem;
  font-weight: 700;
  color: var(--text-primary);
}

.ai-summary {
  font-size: 0.95rem;
  color: var(--text-secondary);
  line-height: 1.6;
  margin: 0;
}

.ai-section {
  display: flex;
  flex-direction: column;
  gap: 8px;
}

.ai-section-title {
  font-size: 0.75rem;
  font-weight: 600;
  text-transform: uppercase;
  color: var(--text-muted);
  letter-spacing: 0.05em;
  border-bottom: 1px solid var(--border-color);
  padding-bottom: 4px;
}

.ai-architecture {
  font-size: 0.875rem;
  color: var(--text-secondary);
  line-height: 1.6;
  margin: 0;
}

.tech-tags {
  display: flex;
  flex-wrap: wrap;
  gap: 8px;
  margin-top: 4px;
}

.tech-tag {
  font-weight: 500;
}

.features-list {
  margin: 0;
  padding-left: 20px;
}

.feat-item {
  font-size: 0.875rem;
  color: var(--text-secondary);
  line-height: 1.6;
  margin-bottom: 4px;
}

.ai-charts-container {
  display: flex;
  flex-direction: column;
  gap: 2rem;
  padding-left: 1.5rem;
  border-left: 1px solid var(--border-color);
  height: 100%;
}

.complexity-score-box {
  display: flex;
  flex-direction: column;
  align-items: center;
  gap: 12px;
}

.complexity-lbl {
  font-size: 0.875rem;
  font-weight: 600;
  color: var(--text-secondary);
}

.custom-bar-charts {
  display: flex;
  flex-direction: column;
  gap: 16px;
}

.custom-chart-row {
  display: flex;
  flex-direction: column;
  gap: 4px;
}

.chart-label-row {
  display: flex;
  justify-content: space-between;
  font-size: 0.825rem;
}

.chart-name {
  color: var(--text-secondary);
  font-weight: 500;
}

.chart-value {
  color: var(--text-muted);
}

@keyframes rotating {
  from { transform: rotate(0deg); }
  to { transform: rotate(360deg); }
}

@media (max-width: 991px) {
  .ai-charts-container {
    padding-left: 0;
    border-left: none;
    margin-top: 2rem;
    padding-top: 2rem;
    border-top: 1px solid var(--border-color);
  }
}
</style>
